Switched to two-stages debootstrap.
Some build-time bugs still to solve, concerning Open vSwitch and debootstrap itself.

diff --git a/devel/uml-init-stub b/devel/uml-init-stub
--- a/devel/uml-init-stub
+++ b/devel/uml-init-stub
@@ -22,35 +22,48 @@
 
 # Exit if any of the commands below fails (note that this will cause a
 # harmless panic in the UML kernel, because it implies killing init).
-#set -e
+set -e
 
 # Extra assignments on the UML kernel command line are
 # passed as environment variables to this script.
-# Expected variables are:
+# Expected variables (for stage 1) are:
 # TARGETARCH: target architecture for the filesystem image (i386 or x86_64)
 # WORKDIR: the directory where the filesystem build is taking place
 
-mount -o remount,rw none /
+# The following command is required only if the "rw" argument is not
+# passed on as UML kernel command line argument.
+#mount -o remount,rw none /
 mount -t proc none /proc
 mount -t sysfs none /sys
 mount -t tmpfs none /run
-mount -t devtmpfs none /dev
+# The option to automatically mount devtmpfs may be compiled in the kernel.
+# Note that, even if the host-side /dev is a mountpoint, the UML kernel
+# only sees its own mountpoints, therefore the following test works
+# correctly.
+mountpoint /dev || mount -t devtmpfs none /dev
 
-# Replace resolv.conf in well-known (and writable) locations
-for DIR in /run/{NetworkManager,resolvconf}; do
-	mkdir ${DIR}
-	echo "nameserver 8.8.8.8" > ${DIR}/resolv.conf
-done
+case $(basename $0) in
+	uml-init-stub)
+		# Replace resolv.conf in well-known (and writable) locations
+		for DIR in /run/{NetworkManager,resolvconf}; do
+			mkdir ${DIR}
+			echo "nameserver 8.8.8.8" > ${DIR}/resolv.conf
+		done
 
-# Enable network (required by debootstrap to fetch repository information)
-echo Setting up network...
-ip addr add 10.0.2.15/8 dev eth0
-ip link set eth0 up
-ip route add default dev eth0
+		# Enable network (required by debootstrap to fetch repository information)
+		echo Setting up network...
+		ip addr add 10.0.2.15/8 dev eth0
+		ip link set eth0 up
+		ip route add default dev eth0
 
-cd ${WORKDIR}
+		cd ${WORKDIR}
 
-make do-privileged-tasks TARGET_ARCH=${TARGETARCH}
+		make do-privileged-tasks TARGET_ARCH=${TARGETARCH}
+	;;
+	uml-init-stub-stage2)
+		/debootstrap/debootstrap --second-stage || { echo "Failed debootstrap stage 2. Log follows:"; cat /debootstrap/debootstrap.log; }
+	;;
+esac
 
 /sbin/poweroff -f
 
